/**
 * Alias dictionary for technical skills (docs/03-MATCHING-SPEC.md § Skills).
 * `name` is the canonical display name; aliases are matched case-insensitively
 * unless `caseSensitive` is set (for short terms that collide with common words).
 */
export interface SkillDefinition {
  readonly name: string;
  readonly aliases: readonly string[];
  readonly caseSensitive?: boolean;
}

export const SKILL_CATALOG: readonly SkillDefinition[] = [
  // Languages
  { name: 'JavaScript', aliases: ['javascript', 'js', 'ecmascript', 'es6'] },
  { name: 'TypeScript', aliases: ['typescript', 'ts'] },
  { name: 'Java', aliases: ['java'] },
  { name: 'Python', aliases: ['python', 'python3'] },
  { name: 'C#', aliases: ['c#', 'csharp', 'c sharp'] },
  { name: 'C++', aliases: ['c++', 'cpp'] },
  { name: 'Go', aliases: ['golang'] },
  { name: 'Go', aliases: ['Go'], caseSensitive: true },
  { name: 'PHP', aliases: ['php'] },
  { name: 'Ruby', aliases: ['ruby'] },
  { name: 'Kotlin', aliases: ['kotlin'] },
  { name: 'Swift', aliases: ['swift'] },
  { name: 'Scala', aliases: ['scala'] },
  { name: 'Rust', aliases: ['rust'] },
  { name: 'Dart', aliases: ['dart'] },
  { name: 'COBOL', aliases: ['cobol'] },
  { name: 'ABAP', aliases: ['abap'] },
  { name: 'Visual Basic', aliases: ['visual basic', 'vb.net', 'vba'] },
  { name: 'Bash', aliases: ['bash', 'shell scripting'] },
  { name: 'PowerShell', aliases: ['powershell'] },
  { name: 'HTML', aliases: ['html', 'html5'] },
  { name: 'CSS', aliases: ['css', 'css3'] },
  { name: 'Sass', aliases: ['sass', 'scss'] },
  { name: 'SQL', aliases: ['sql', 't-sql', 'tsql', 'pl/sql', 'plsql'] },
  // Frontend
  { name: 'React', aliases: ['react', 'react.js', 'reactjs'] },
  { name: 'React Native', aliases: ['react native'] },
  { name: 'Angular', aliases: ['angular', 'angularjs', 'angular.js'] },
  { name: 'Vue.js', aliases: ['vue', 'vue.js', 'vuejs'] },
  { name: 'Next.js', aliases: ['next.js', 'nextjs'] },
  { name: 'Redux', aliases: ['redux'] },
  { name: 'jQuery', aliases: ['jquery'] },
  { name: 'Bootstrap', aliases: ['bootstrap'] },
  { name: 'Tailwind CSS', aliases: ['tailwind', 'tailwindcss', 'tailwind css'] },
  { name: 'Flutter', aliases: ['flutter'] },
  // Backend
  { name: 'Node.js', aliases: ['node', 'node.js', 'nodejs'] },
  { name: 'Express', aliases: ['express.js', 'expressjs'] },
  { name: 'Express', aliases: ['Express'], caseSensitive: true },
  { name: 'NestJS', aliases: ['nestjs', 'nest.js'] },
  { name: 'Spring', aliases: ['spring', 'spring framework'] },
  { name: 'Spring Boot', aliases: ['spring boot', 'springboot'] },
  { name: 'Hibernate', aliases: ['hibernate', 'jpa'] },
  { name: '.NET', aliases: ['.net', 'dotnet', '.net core', 'asp.net', 'asp.net core', 'net core'] },
  { name: 'Django', aliases: ['django'] },
  { name: 'Flask', aliases: ['flask'] },
  { name: 'FastAPI', aliases: ['fastapi'] },
  { name: 'Laravel', aliases: ['laravel'] },
  { name: 'Symfony', aliases: ['symfony'] },
  { name: 'Ruby on Rails', aliases: ['ruby on rails', 'rails'] },
  { name: 'GraphQL', aliases: ['graphql'] },
  { name: 'REST', aliases: ['rest', 'restful', 'api rest', 'apis rest', 'rest api', 'rest apis'] },
  { name: 'Microservices', aliases: ['microservicios', 'microservices', 'microservicio'] },
  // Data
  { name: 'PostgreSQL', aliases: ['postgresql', 'postgres'] },
  { name: 'MySQL', aliases: ['mysql'] },
  { name: 'SQL Server', aliases: ['sql server', 'sqlserver', 'mssql'] },
  { name: 'Oracle', aliases: ['oracle'] },
  { name: 'MongoDB', aliases: ['mongodb', 'mongo'] },
  { name: 'Redis', aliases: ['redis'] },
  { name: 'Elasticsearch', aliases: ['elasticsearch', 'elastic search'] },
  { name: 'Kafka', aliases: ['kafka'] },
  { name: 'RabbitMQ', aliases: ['rabbitmq'] },
  { name: 'Spark', aliases: ['spark', 'pyspark'] },
  { name: 'Pandas', aliases: ['pandas'] },
  { name: 'Power BI', aliases: ['power bi', 'powerbi'] },
  { name: 'Tableau', aliases: ['tableau'] },
  { name: 'Excel', aliases: ['excel'] },
  { name: 'Machine Learning', aliases: ['machine learning', 'aprendizaje automatico'] },
  { name: 'TensorFlow', aliases: ['tensorflow'] },
  { name: 'PyTorch', aliases: ['pytorch'] },
  // Cloud / DevOps
  { name: 'AWS', aliases: ['aws', 'amazon web services'] },
  { name: 'Azure', aliases: ['azure'] },
  { name: 'GCP', aliases: ['gcp', 'google cloud', 'google cloud platform'] },
  { name: 'Docker', aliases: ['docker'] },
  { name: 'Kubernetes', aliases: ['kubernetes', 'k8s'] },
  { name: 'Terraform', aliases: ['terraform'] },
  { name: 'Jenkins', aliases: ['jenkins'] },
  { name: 'CI/CD', aliases: ['ci/cd', 'cicd'] },
  { name: 'Git', aliases: ['git', 'github', 'gitlab', 'bitbucket'] },
  { name: 'Linux', aliases: ['linux', 'unix'] },
  // Practices / tools
  { name: 'Scrum', aliases: ['scrum'] },
  { name: 'Agile', aliases: ['agile', 'metodologias agiles', 'metodologia agil'] },
  { name: 'Jira', aliases: ['jira'] },
  { name: 'Selenium', aliases: ['selenium'] },
  { name: 'Cypress', aliases: ['cypress'] },
  { name: 'Jest', aliases: ['jest'] },
  { name: 'JUnit', aliases: ['junit'] },
  { name: 'Postman', aliases: ['postman'] },
  { name: 'SAP', aliases: ['sap'] },
  { name: 'Salesforce', aliases: ['salesforce'] },
  { name: 'Figma', aliases: ['figma'] },
];
